/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.SwingUtilities;

import org.example.Repo.FileTaskRepo;
import org.example.UI.UI;
import org.example.model.Task;
import org.example.service.TaskService;

import com.formdev.flatlaf.FlatLightLaf;

public class App {

public class Main {
    public static void main(String[] args) {

        // flatlaf to make the ui look better in my opinion
        FlatLightLaf.setup();
        
        // running app
        SwingUtilities.invokeLater(() -> {

            FileTaskRepo repo = new FileTaskRepo();
            TaskService service = new TaskService(repo);

            UI ui = new UI(service);
            ui.setVisible(true);

            // fo testing toString()
            for (Task allTask : service.getAllTasks()) {
                System.out.println(allTask.toString());
            }
        });
    }
}
}
